comment "Remove existing items";
removeAllWeapons player;
removeAllItems player;
removeAllAssignedItems player;
removeUniform player;
removeVest player;
removeBackpack player;
removeHeadgear player;
removeGoggles player;

comment "Add containers";
player forceAddUniform "VSM_AOR1_Crye_SS_Camo";
for "_i" from 1 to 9 do {player addItemToUniform "ACE_elasticBandage";};
for "_i" from 1 to 9 do {player addItemToUniform "ACE_packingBandage";};
for "_i" from 1 to 5 do {player addItemToUniform "ACE_CableTie";};
player addItemToUniform "ACE_EarPlugs";
player addItemToUniform "ACE_EntrenchingTool";
player addItemToUniform "ACE_microDAGR";
player addItemToUniform "ACE_morphine";
player addItemToUniform "ACE_tourniquet";
player addItemToUniform "ACE_Flashlight_XL50";
player addItemToUniform "ACE_IR_Strobe_Item";
player addVest "VSM_FAPC_Breacher_AOR1";
for "_i" from 1 to 10 do {player addItemToVest "1Rnd_HE_Grenade_shell";};
for "_i" from 1 to 8 do {player addItemToVest "rhsusf_5Rnd_00Buck";};
for "_i" from 1 to 4 do {player addItemToVest "SmokeShell";};
for "_i" from 1 to 2 do {player addItemToVest "rhs_mag_m67";};
for "_i" from 1 to 2 do {player addItemToVest "rhsusf_mag_17Rnd_9x19_JHP";};
for "_i" from 1 to 8 do {player addItemToVest "30Rnd_556x45_Stanag";};
player addBackpack "VSM_AOR1_Backpack_Kitbag";
player addItemToBackpack "rhs_weap_M590_5RD";
for "_i" from 1 to 6 do {player addItemToBackpack "30Rnd_556x45_Stanag";};
player addItemToBackpack "30Rnd_556x45_Stanag_Tracer_Red";
player addHeadgear "VSM_Mich2000_2_aor1";
player addGoggles "rhsusf_shemagh2_gogg_tan";

comment "Add weapons";
player addWeapon "SMA_M4_GL_SM";
player addPrimaryWeaponItem "SMA_FLASHHIDER2";
player addPrimaryWeaponItem "SMA_SFPEQ_M4TOP_BLK";
player addPrimaryWeaponItem "SMA_eotech552_3XDOWN_des";
player addWeapon "rhsusf_weap_glock17g4";

comment "Add items";
player linkItem "ItemMap";
player linkItem "ItemCompass";
player linkItem "tf_microdagr";
player linkItem "tf_anprc152_1";

comment "Set identity";
player setFace "WhiteHead_02";
player setSpeaker "ace_novoice";
